- name: Create alertmanager CRD
  k8s:
    state: present
    definition: "{{ lookup('file', 'alertmanager.crd.yaml') | from_yaml }}"

- name: Create podmonitor CRD
  k8s:
    state: present
    definition: "{{ lookup('file', 'podmonitor.crd.yaml') | from_yaml }}"

- name: Create prometheus CRD
  k8s:
    state: present
    definition: "{{ lookup('file', 'prometheus.crd.yaml') | from_yaml }}"

- name: Create prometheusrule CRD
  k8s:
    state: present
    definition: "{{ lookup('file', 'prometheusrule.crd.yaml') | from_yaml }}"

- name: Create servicemonitor CRD
  k8s:
    state: present
    definition: "{{ lookup('file', 'servicemonitor.crd.yaml') | from_yaml }}"

- name: Copy prometheus-operator chart
  copy:
    src: charts/prometheus-operator
    dest: /home/{{ ansible_user }}

- name: Install prometheus-operator helm chart
  shell: |-
    helm install stable/prometheus-operator \
      --version {{ prometheus_operator_version }} \
      --name prometheus-operator \
      --namespace monitoring \
      --values values.yaml
  args:
    chdir: /home/{{ ansible_user }}/prometheus-operator
