apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: name-virtual-host-ingress
  namespace: default
spec:
  rules:
  - host: drone.rbwescaledrone-dev.rbwscaws.jdxlabs.com
    http:
      paths:
      - backend:
          serviceName: drone-drone
          servicePort: 80
