---
- hosts: k3s-cluster
  gather_facts: yes
  become: yes
  roles:
    - { role: download }

- hosts: master
  become: yes
  roles:
    - { role: k3s/master }

- hosts: node
  become: yes
  roles:
    - { role: k3s/node }

- hosts: bastion
  become: no
  roles:
    - { role: k3s/bastion }
