- hosts: k3s-cluster
  gather_facts: yes
  become: yes
  roles:
    - { role: k3s/download }

- hosts: masters
  become: yes
  roles:
    - { role: k3s/master }

- hosts: nodes
  become: yes
  roles:
    - { role: k3s/node }

- hosts: bastions
  become: no
  roles:
    - { role: k3s/bastion }
    - { role: python-k8s-modules }
    - { role: helm }
    - { role: cert-manager }
    - { role: drone }
