- name: Download kubectl
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v1.15.0/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    mode: 0755
    force: yes

- name: Create directory .kube
  file:
    path: /home/{{ ansible_user }}/.kube
    state: directory
    owner: "{{ ansible_user }}"

- name: Create kubectl
  copy:
    dest: /home/{{ ansible_user }}/.kube/config
    content: |
      {{ hostvars[groups['master'][0]]['kubectl_config'] }}

- name: Install helm (download script)
  get_url:
    url: https://git.io/get_helm.sh
    dest: /home/{{ ansible_user }}/get_helm.sh
    mode: 0700

- name: Install helm (execute script)
  shell: /home/{{ ansible_user }}/get_helm.sh

- name: Configure tiller
  shell: |
    kubectl -n kube-system create serviceaccount tiller

    kubectl create clusterrolebinding tiller \
      --clusterrole=cluster-admin \
      --serviceaccount=kube-system:tiller

    helm init --service-account tiller
  become_user: "{{ ansible_user }}"
  become: false
